version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: ppcustom_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ppcustom
      POSTGRES_PASSWORD: ppcustom123
      POSTGRES_DB: ppcustom_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: